
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Warehouse.Models
{

using System;
    using System.Collections.Generic;
    
public partial class News
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Introduce { get; set; }

    public string Content { get; set; }

    public string Image { get; set; }

    public Nullable<System.DateTime> DateSubmitted { get; set; }

    public string Poster { get; set; }

    public string Alias_SEO { get; set; }

    public int View { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
