// <auto-generated />
namespace Warehouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addlisttableTranslation2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlisttableTranslation2));
        
        string IMigrationMetadata.Id
        {
            get { return "201901231533381_add-list-table-Translation2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
