// <auto-generated />
namespace Warehouse.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addlisttableTranslation3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlisttableTranslation3));
        
        string IMigrationMetadata.Id
        {
            get { return "201901231534144_add-list-table-Translation3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
