//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoShop
    {
        public int Id { get; set; }
        public string ShopName { get; set; }
        public string Logo { get; set; }
        public string Phone { get; set; }
        public string Zalo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Fanpage { get; set; }
        public string Introduce_Shop { get; set; }
        public string Contact_Info { get; set; }
        public string Google_Map { get; set; }
        public string TextFooter { get; set; }
        public string GoogleAnalytics { get; set; }
        public string SalesPolicy { get; set; }
        public string ShoppingGuide { get; set; }
    }
}
